version = 0.1

[default.deploy.parameters]
stack_name = "s3-video-upload"
resolve_s3 = true
s3_prefix = "s3-video-upload"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
